### ISSUE TITLE
Get all adventure info

### ISSUE THREAD

**Issue by probably-not-a-cat** [AdventureLookup/adventurelookup-backend#19]
Make an api call that gets all the info of an adventure given an id.

**Comment by probably-not-a-cat** [comment]
I have already started working on this. But if you got some ideas on how to do this feel free to post them here.

**Comment by whonut** [comment]
I've knocked something up for this, mind if I submit a PR?

**Comment by probably-not-a-cat** [comment]
Sure, I won't say no to someone who has better code. :)
