### ISSUE TITLE
Data should be stored in a data container or be host bound to prevent accidental data loss

### ISSUE THREAD

**Issue by pejter** [AdventureLookup/adventurelookup-backend#4]
I'm opting for host-bind since it's easier and more intuitive. Also less risk of accidental deletion.

**Comment by cpnielsen** [comment]
Data for postgres is already stored in a host-bound, but I forgot to make it relative (so it lives in your docker base setup somewhere).

**Comment by pejter** [comment]
It's a named volume. Those are managed by Docker and that means they can be accidentally deleted. See [Docker-compose volumes](https://docs.docker.com/compose/compose-file/#volumes-volume-driver)
